### ISSUE TITLE
Error, please help

### ISSUE THREAD

**Issue by Peny22888** [mishalhossin/Discord-AI-Chatbot#108]
![Screenshot_20230528_140807](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/110277810/faa8007d-f12c-4cfd-809c-6b3dcd00b22e)

**Comment by mishalhossin** [comment]
i cant even see the full log

**Comment by Peny22888** [comment]
Sorry, but I do not know where to get them, I just use hosting on the pterodactyl panel, I reviewed all the files, but I did not find the logs folder, because on other hosts that I used before, the logs were in the folder

**Comment by mishalhossin** [comment]
> Sorry, but I do not know where to get them, I just use hosting on the pterodactyl panel, I reviewed all the files, but I did not find the logs folder, because on other hosts that I used before, the logs were in the folder

is there still the same error ?

**Comment by Peny22888** [comment]
Of course, where will she go

**Comment by mishalhossin** [comment]
> Of course, where will she go

okay can i just get the `error` as raw text instead of a screenshot ?

**Comment by mishalhossin** [comment]
also did you remove the lang folder ?

**Comment by mishalhossin** [comment]
can you try to update your repo also you actually get gpt4 now if you do

**Comment by Peny22888** [comment]
The comma seems to be present, that's how you asked, an error in text form 



Traceback (most recent call last):
File "/home/container/main.py", line 51, in <module>
current_language = load_current_language() File "/home/container/main.py", line 48, in load_current_language
current_language = json.load(lang_file) File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
return loads (fp.read(),
File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.9/json/decoder.py ", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.9/json/decoder.py line 353, in raw_decode
obj, end = self.scan_once(s, idx) json.decoder.JSONDecodeError: Expecting ',' delimiter: line 2 column 561 (char 562)

**Comment by mishalhossin** [comment]
> The comma seems to be present, that's how you asked, an error in text form
> 
> Traceback (most recent call last): File "/home/container/main.py", line 51, in current_language = load_current_language() File "/home/container/main.py", line 48, in load_current_language current_language = json.load(lang_file) File "/usr/local/lib/python3.9/json/**init**.py", line 293, in load return loads (fp.read(), File "/usr/local/lib/python3.9/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/usr/local/lib/python3.9/json/decoder.py ", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/local/lib/python3.9/json/decoder.py line 353, in raw_decode obj, end = self.scan_once(s, idx) json.decoder.JSONDecodeError: Expecting ',' delimiter: line 2 column 561 (char 562)

I checked the JSON again and it seems to be correct

**Comment by mishalhossin** [comment]
Can you update your cloned project and try again ?

**Comment by Peny22888** [comment]
Still the same mistake

**Comment by Peny22888** [comment]
I solved this problem, it was extremely stupid, and consisted in the fact that there were characters in double quotes in the text, I just put them in single quotes

**Comment by Peny22888** [comment]
But I still have a question, please answer. Is there any way to make the answers ONLY in Russian?

**Comment by dadaoerv** [comment]
> But I still have a question, please answer. Is there any way to make the answers ONLY in Russian?

![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/46274596/683ab12f-a559-472c-a44a-270b273adbba)

**Comment by Peny22888** [comment]
With this method, sooner or later he begins to speak the same English

**Comment by dadaoerv** [comment]
> With this method, sooner or later he begins to speak the same English

it didn't happen to me.
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/46274596/4253857f-b15b-4be1-bb66-ba6c487c7d64)

**Comment by Peny22888** [comment]
Why do I have so many problems all the time, aaaaaaaaaaa, I got an error like that person with deepai

**Comment by mishalhossin** [comment]
> But I still have a question, please answer. Is there any way to make the answers ONLY in Russian?

I will add a lang/lang.ru file

then you could edit the main.py to select ru instead of en
