### ISSUE TITLE
Can I use Discord-AI-Chatbot/model/aiassist.py in my MIT licensed bot?

### ISSUE THREAD

**Issue by mak448a** [mishalhossin/Discord-AI-Chatbot#110]
Can I use the [script](https://github.com/mishalhossin/Discord-AI-Chatbot/blob/main/model/aiassist.py) that calls the ChatGPT API in [my MIT licensed bot?](https://github.com/mak448a/Stable-Diffusion-Bot)

**Comment by mishalhossin** [comment]
> Can I use the [script](https://github.com/mishalhossin/Discord-AI-Chatbot/blob/main/model/aiassist.py) that calls the ChatGPT API in [my MIT licensed bot?](https://github.com/mak448a/Stable-Diffusion-Bot)

I guess you gotta give credit and you are good

**Comment by mishalhossin** [comment]
I guess I will change the license to Apache

**Comment by mak448a** [comment]
Anyway, thanks!

**Comment by mishalhossin** [comment]
> > I guess I will change the license to Apache
> 
> Sure, but don't you have to contact all of the contributors to change the license?

oh okay mb

**Comment by mishalhossin** [comment]
I guess i will keep gpl licence

**Comment by mishalhossin** [comment]
you will have to change your licence if you want to use the code

**Comment by mishalhossin** [comment]
I should totally get a lawyer

**Comment by mak448a** [comment]
Ok.
