### ISSUE TITLE
aiohttp

### ISSUE THREAD

**Issue by 220m** [mishalhossin/Discord-AI-Chatbot#112]
I am encountering this error when running it via cmd with "python main.py"

D:\AI\Discord AI\Discord-AI-Chatbot>python main.py
Traceback (most recent call last):
  File "D:\AI\Discord AI\Discord-AI-Chatbot\main.py", line 6, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

**Comment by mishalhossin** [comment]
Run `pip install -r requirements.txt`

**Comment by 220m** [comment]
Thank you so much for the fast answer! you are putty really much effort in this, thank you.

**Comment by 220m** [comment]
discord.errors.HTTPException: 400 Bad Request (error code: 30034): Max number of daily application command creates has been reached (200)

what is about this? I saw it on issues already but I have a bot created months ago and just reset the token why does that not work?

**Comment by mishalhossin** [comment]
> discord.errors.HTTPException: 400 Bad Request (error code: 30034): Max number of daily application command creates has been reached (200)
> 
> what is about this? I saw it on issues already but I have a bot created months ago and just reset the token why does that not work?

try on a new bot or wait for one day
