### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by 220m** [mishalhossin/Discord-AI-Chatbot#113]
I just created a fresh bot and have only 1 bot in dev portal. how to fix this i dont have this with any other bots?

discord.errors.HTTPException: 400 Bad Request (error code: 30034): Max number of daily application command creates has been reached (200)

what is about this? I saw it on issues already but I have a bot created months ago and just reset the token why does that not work?

**Comment by AbandonedCart** [comment]
It's by the account, not the application. Take a break, come back tomorrow.
