### ISSUE TITLE
Bot name and profile picture auto changed by non admin

### ISSUE THREAD

**Issue by Doocter** [mishalhossin/Discord-AI-Chatbot#120]

**Comment by mishalhossin** [comment]
okay

**Comment by mishalhossin** [comment]
> why you stealing tokens?

Read the code first

**Comment by mishalhossin** [comment]
only owner of the bot can change it using the /changeusr and /pfp command

**Comment by mishalhossin** [comment]
😅 wait my bad i forgot to add `@commands.is_owner()` to /pfp command my bad 


https://github.com/mishalhossin/Discord-AI-Chatbot/commit/b73253f1539ece087fb41b7fc926cd24c0981095

**Comment by mishalhossin** [comment]
@Doocter Please update your discord bot

**Comment by mishalhossin** [comment]
> sure, also make sure you changed for name and profile picture both right?

Yea i just forgot to add it to the pfp change
