### ISSUE TITLE
Error: FileNotFoundError when running bot on NAS without Docker

### ISSUE THREAD

**Issue by Virusf** [mishalhossin/Discord-AI-Chatbot#125]
Hello,

I'm trying to run the bot on my NAS, but I can't install Docker on my Nas. However, I do have Python installed and I encountered the following problem:

```
Traceback (most recent call last):
  File "/main.py", line 24, in <module>
    with open('config.json') as config_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
```

In my search for a solution, I came across the following code snippet:

```
BASE_PATH = os.path.dirname(os.path.realpath(__file__))
with open(BASE_PATH+'/config.json') as config_file:
    config = json.load(config_file)
```
    
Here is a little code improvement.
Thank you for your attention.

ps: I apologize because I do not speak English and the message little was not clear.

**Comment by mishalhossin** [comment]
@Virusf I would like to inform you that I have made some important changes to the configuration file. We have transitioned from using JSON to YAML format. This update brings a more streamlined and efficient structure to our configuration.

**Comment by mishalhossin** [comment]
> OK thank you for the information and great work on this project

Stay up-to-date by joining our Discord community at https://discord.gg/aJvH48QZ.
