### ISSUE TITLE
Modify aiassist for KoboldAI.

### ISSUE THREAD

**Issue by elsowe-chan** [mishalhossin/Discord-AI-Chatbot#127]
hi i would like to know if you could modify the aiassit.py file  to make it compatible with koboldai?

sorry if this is not the right place to send this
thank you in advance for your reply

**Comment by mishalhossin** [comment]
You can try looking into https://github.com/Haidra-Org/AI-Horde-CLI and modify it to your needs

**Comment by elsowe-chan** [comment]
actually i have already get the api endpoint that i need the header and the data but i don't have the competence to adapt the aiassit.py file this is why i ask here but thanks anyways for your reply

**Comment by mishalhossin** [comment]
Maybe join their discord https://discord.com/invite/3DxrhksKzn
