### ISSUE TITLE
Trying to install the poe-api package in Replit.

### ISSUE THREAD

**Issue by okkkkoo** [mishalhossin/Discord-AI-Chatbot#137]
Trying to install the poe-api package in Replit.
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/77115336/f7f3c847-0ef1-42a1-9a24-16eab6614671)

**Comment by enemyalert** [comment]
Fork again this [repository](https://replit.com/github/mishalhossin/Discord-AI-Chatbot) because as of now `poe-api` has been removed due to its error and inconsistencies. [Recent change](https://github.com/mishalhossin/Discord-AI-Chatbot/commit/3124a3a63693fa51bd1cd56efd6c36e2527b1d94)
