### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by IntrovertedFL** [mishalhossin/Discord-AI-Chatbot#142]
```
discordbot  | Task exception was never retrieved
discordbot  | future: <Task finished name='Task-343' coro=<on_message.<locals>.generate_response_in_thread() done, defined at /app/main.py:420> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
discordbot  | Traceback (most recent call last):
discordbot  |   File "/app/main.py", line 423, in generate_response_in_thread
discordbot  |     response = await generate_response(prompt)
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/app/main.py", line 150, in generate_response
discordbot  |     response = await aiassist.Completion.create(prompt=prompt)
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/app/model/aiassist.py", line 59, in create
discordbot  |     response = Completion.__load_json(content)
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/app/model/aiassist.py", line 67, in __load_json
discordbot  |     to_json = json.loads(split[1])
discordbot  |               ^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
discordbot  |     return _default_decoder.decode(s)
discordbot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
discordbot  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
discordbot  |     raise JSONDecodeError("Expecting value", s, err.value) from None
discordbot  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
discordbot  | Task exception was never retrieved
discordbot  | future: <Task finished name='Task-352' coro=<on_message.<locals>.generate_response_in_thread() done, defined at /app/main.py:420> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
discordbot  | Traceback (most recent call last):
discordbot  |   File "/app/main.py", line 423, in generate_response_in_thread
discordbot  |     response = await generate_response(prompt)
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/app/main.py", line 150, in generate_response
discordbot  |     response = await aiassist.Completion.create(prompt=prompt)
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/app/model/aiassist.py", line 59, in create
discordbot  |     response = Completion.__load_json(content)
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/app/model/aiassist.py", line 67, in __load_json
discordbot  |     to_json = json.loads(split[1])
discordbot  |               ^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
discordbot  |     return _default_decoder.decode(s)
discordbot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
discordbot  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
discordbot  |     raise JSONDecodeError("Expecting value", s, err.value) from None
discordbot  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Kerman-ap** [comment]
getting same issue here

**Comment by Kerman-ap** [comment]
@IntrovertedFL Still getting it
`[2023-06-11 20:47:20] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\one\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "G:\Downloads\GPT Bot\Discord-AI-Chatbot\main.py", line 418, in on_message
    search_results = await search(message.content)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Downloads\GPT Bot\Discord-AI-Chatbot\main.py", line 254, in search
    search_query = await get_query(prompt)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Downloads\GPT Bot\Discord-AI-Chatbot\main.py", line 237, in get_query
    req = await aiassist.Completion.create(prompt=fullprompt)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Downloads\GPT Bot\Discord-AI-Chatbot\model\aiassist.py", line 59, in create
    response = Completion.__load_json(content)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Downloads\GPT Bot\Discord-AI-Chatbot\model\aiassist.py", line 67, in __load_json
    to_json = json.loads(split[1])
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\one\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\one\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\one\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by IntrovertedFL** [comment]
I just updated my fork, and so far no errors. *fingers crossed*

**Comment by IntrovertedFL** [comment]
Just received this error after about 25/30 messages for no reason. 

```
discordbot  | Task exception was never retrieved
discordbot  | future: <Task finished name='Task-458' coro=<on_message.<locals>.generate_response_in_thread() done, defined at /app/main.py:435> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
discordbot  | Traceback (most recent call last):
discordbot  |   File "/app/main.py", line 438, in generate_response_in_thread
discordbot  |     response = await generate_response(prompt)
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/app/main.py", line 154, in generate_response
discordbot  |     response = await aiassist.Completion.create(prompt=full_prompt)
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/app/model/aiassist.py", line 59, in create
discordbot  |     response = Completion.__load_json(content)
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/app/model/aiassist.py", line 67, in __load_json
discordbot  |     to_json = json.loads(split[1])
discordbot  |               ^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
discordbot  |     return _default_decoder.decode(s)
discordbot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
discordbot  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
discordbot  |     raise JSONDecodeError("Expecting value", s, err.value) from None
discordbot  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
discordbot  | Task exception was never retrieved
discordbot  | future: <Task finished name='Task-470' coro=<on_message.<locals>.generate_response_in_thread() done, defined at /app/main.py:435> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
discordbot  | Traceback (most recent call last):
discordbot  |   File "/app/main.py", line 438, in generate_response_in_thread
discordbot  |     response = await generate_response(prompt)
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/app/main.py", line 154, in generate_response
discordbot  |     response = await aiassist.Completion.create(prompt=full_prompt)
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/app/model/aiassist.py", line 59, in create
discordbot  |     response = Completion.__load_json(content)
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/app/model/aiassist.py", line 67, in __load_json
discordbot  |     to_json = json.loads(split[1])
discordbot  |               ^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
discordbot  |     return _default_decoder.decode(s)
discordbot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
discordbot  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
discordbot  |     raise JSONDecodeError("Expecting value", s, err.value) from None
discordbot  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by mishalhossin** [comment]
> Just received this error after about 25/30 messages for no reason.
> 
> ```
> discordbot  | Task exception was never retrieved
> discordbot  | future: <Task finished name='Task-458' coro=<on_message.<locals>.generate_response_in_thread() done, defined at /app/main.py:435> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
> discordbot  | Traceback (most recent call last):
> discordbot  |   File "/app/main.py", line 438, in generate_response_in_thread
> discordbot  |     response = await generate_response(prompt)
> discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> discordbot  |   File "/app/main.py", line 154, in generate_response
> discordbot  |     response = await aiassist.Completion.create(prompt=full_prompt)
> discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> discordbot  |   File "/app/model/aiassist.py", line 59, in create
> discordbot  |     response = Completion.__load_json(content)
> discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> discordbot  |   File "/app/model/aiassist.py", line 67, in __load_json
> discordbot  |     to_json = json.loads(split[1])
> discordbot  |               ^^^^^^^^^^^^^^^^^^^^
> discordbot  |   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
> discordbot  |     return _default_decoder.decode(s)
> discordbot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> discordbot  |   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
> discordbot  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> discordbot  |   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
> discordbot  |     raise JSONDecodeError("Expecting value", s, err.value) from None
> discordbot  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> discordbot  | Task exception was never retrieved
> discordbot  | future: <Task finished name='Task-470' coro=<on_message.<locals>.generate_response_in_thread() done, defined at /app/main.py:435> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
> discordbot  | Traceback (most recent call last):
> discordbot  |   File "/app/main.py", line 438, in generate_response_in_thread
> discordbot  |     response = await generate_response(prompt)
> discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> discordbot  |   File "/app/main.py", line 154, in generate_response
> discordbot  |     response = await aiassist.Completion.create(prompt=full_prompt)
> discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> discordbot  |   File "/app/model/aiassist.py", line 59, in create
> discordbot  |     response = Completion.__load_json(content)
> discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> discordbot  |   File "/app/model/aiassist.py", line 67, in __load_json
> discordbot  |     to_json = json.loads(split[1])
> discordbot  |               ^^^^^^^^^^^^^^^^^^^^
> discordbot  |   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
> discordbot  |     return _default_decoder.decode(s)
> discordbot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> discordbot  |   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
> discordbot  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> discordbot  |   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
> discordbot  |     raise JSONDecodeError("Expecting value", s, err.value) from None
> discordbot  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```

ah shit here we go again

**Comment by mishalhossin** [comment]
can you set make history in `config.yml` to 4 for now ?

**Comment by IntrovertedFL** [comment]
Yes, doing that now.

**Comment by IntrovertedFL** [comment]
CHanged max_history to 4, and spun back up and got 1 error as soon as it started and the other the second questions asked. 

```
discordbot  | 2023-06-11 14:05:28 ERROR    discord.client Ignoring exception in on_message
discordbot  | Traceback (most recent call last):
discordbot  |   File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
discordbot  |     await coro(*args, **kwargs)
discordbot  |   File "/app/main.py", line 386, in on_message
discordbot  |     if message.reference and (message.reference.resolved.author != bot.user or message.reference.resolved.embeds):
discordbot  |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  | AttributeError: 'NoneType' object has no attribute 'author'
discordbot  | Task exception was never retrieved
discordbot  | future: <Task finished name='Task-66' coro=<on_message.<locals>.generate_response_in_thread() done, defined at /app/main.py:435> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
discordbot  | Traceback (most recent call last):
discordbot  |   File "/app/main.py", line 438, in generate_response_in_thread
discordbot  |     response = await generate_response(prompt)
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/app/main.py", line 154, in generate_response
discordbot  |     response = await aiassist.Completion.create(prompt=full_prompt)
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/app/model/aiassist.py", line 59, in create
discordbot  |     response = Completion.__load_json(content)
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/app/model/aiassist.py", line 67, in __load_json
discordbot  |     to_json = json.loads(split[1])
discordbot  |               ^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
discordbot  |     return _default_decoder.decode(s)
discordbot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
discordbot  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
discordbot  |     raise JSONDecodeError("Expecting value", s, err.value) from None
discordbot  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by mishalhossin** [comment]
*dies*

**Comment by mishalhossin** [comment]
can you try running outside a docker ?

**Comment by IntrovertedFL** [comment]
Yes, I will do that now.

**Comment by IntrovertedFL** [comment]
After about the 5th message 

```
Task exception was never retrieved
future: <Task finished name='Task-93' coro=<on_message.<locals>.generate_response_in_thread() done, defined at /home/aaron/Dev/suzy/main.py:435> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/home/aaron/Dev/suzy/main.py", line 438, in generate_response_in_thread
    response = await generate_response(prompt)
  File "/home/aaron/Dev/suzy/main.py", line 154, in generate_response
    response = await aiassist.Completion.create(prompt=full_prompt)
  File "/home/aaron/Dev/suzy/model/aiassist.py", line 59, in create
    response = Completion.__load_json(content)
  File "/home/aaron/Dev/suzy/model/aiassist.py", line 67, in __load_json
    to_json = json.loads(split[1])
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by maxcurrent420** [comment]
Yeah was working for me for a number of messages and then same issue.

**Comment by NginREV** [comment]
I getting same issue here

**Comment by tiudvek** [comment]
same.
