### ISSUE TITLE
Removing /gif ?

### ISSUE THREAD

**Issue by Eevee-Gaming** [mishalhossin/Discord-AI-Chatbot#147]
_I do have a poor knowledge in English, some errors may be in the request below._
Hi. I have tried your bot, which is extremely impressive and cool, but there is something that annoys me.
This is the /gif command, which is not too "AI" related, but i think it has been put in just for fun.
Due to my very poor knowledge in Python, i couldn't remove it proprely, and the coding keeps generating errors everytime, which annoys me too.

So, i want to know how to remove this command by deleting the correct strings, or adding a optional command.

Thank you putting time into reading this text, have a nice day.

**Comment by mishalhossin** [comment]
> _I do have a poor knowledge in English, some errors may be in the request below._ Hi. I have tried your bot, which is extremely impressive and cool, but there is something that annoys me. This is the /gif command, which is not too "AI" related, but i think it has been put in just for fun. Due to my very poor knowledge in Python, i couldn't remove it proprely, and the coding keeps generating errors everytime, which annoys me too.
> 
> So, i want to know how to remove this command by deleting the correct strings, or adding a optional command.
> 
> Thank you putting time into reading this text, have a nice day.

just remove it cuh

**Comment by mishalhossin** [comment]
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/91066601/e3dd26b8-bfce-4495-9bb7-04c85ca6a10a)
just select and remove in main.py
