### ISSUE TITLE
 Unresponsive Bot and Mysterious Error during Picture Generation

### ISSUE THREAD

**Issue by Lorgar-Horusov** [mishalhossin/Discord-AI-Chatbot#149]
A request was made to generate a picture, but after a long wait the bot did not respond and there was no error in the console
![изображение](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/111076114/3f814221-3113-416f-acd8-1708e0d9a03d)

Further, when trying to generate a response from the neural network,
![изображение](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/111076114/df0eca85-db2f-453c-9da4-2ad7e28d2f05)
 the bot did not respond and gave the following error
![изображение](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/111076114/b223d113-d768-44c0-8586-37a443cdde6c)

bot version is the latest

**Comment by enemyalert** [comment]
Already fixed that issue. Read the thread [here](https://github.com/mishalhossin/Discord-AI-Chatbot/issues/148).

**Comment by mishalhossin** [comment]
nvm picture dont work

**Comment by Lorgar-Horusov** [comment]
> Already fixed that issue. Read the thread [here](https://github.com/mishalhossin/Discord-AI-Chatbot/issues/148).

I tried to apply these fixes, but the result was not affected by the error remains
