### ISSUE TITLE
Key error 'choices'

### ISSUE THREAD

**Issue by PeterDBR27** [mishalhossin/Discord-AI-Chatbot#153]
```py
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/container/main.py", line 156, in on_message
    response = await generate_response(instructions, search_results, image_caption, history)
  File "/home/container/utilities/ai_utils.py", line 71, in generate_response
    choices = response_data['choices']
KeyError: 'choices'
```

Yes, i'm using the main, i think it's because my instructions are too big

**Comment by wahitftry** [comment]
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/26300406/4dca0795-ca75-45d2-bdc7-23fcb4e12eb3)
here i added the error from docker

**Comment by chris-ss** [comment]
the same problem

**Comment by IntrovertedFL** [comment]
Same here

**Comment by Yerli-Oyuncu** [comment]
same

**Comment by GameOn2611** [comment]
```Yes I am also getting same error ```

**Comment by mishalhossin** [comment]
> ```python
> Traceback (most recent call last):
>   File "/home/container/.local/lib/python3.9/site-packages/discord/client.py", line 441, in _run_event
>     await coro(*args, **kwargs)
>   File "/home/container/main.py", line 156, in on_message
>     response = await generate_response(instructions, search_results, image_caption, history)
>   File "/home/container/utilities/ai_utils.py", line 71, in generate_response
>     choices = response_data['choices']
> KeyError: 'choices'
> ```
> 
> Yes, i'm using the main, i think it's because my instructions are too big

Die
