### ISSUE TITLE
Cosmic name seems to be wrong.

### ISSUE THREAD

**Issue by NginREV** [mishalhossin/Discord-AI-Chatbot#157]
`    app_commands.Choice(name='Cosmic 🌌', value='COMIC_V2'),`

Name is `Cosmic` but value is `COMIC_V2`

**Comment by mishalhossin** [comment]
> ` app_commands.Choice(name='Cosmic 🌌', value='COMIC_V2'),`
> 
> Name is `Cosmic` but value is `COMIC_V2`

yea enum values are diffrent i know its not like you will see it in the bot or anything
