### ISSUE TITLE
I apologize for any inconvenience caused. It seems that there was an error preventing the delivery of my message.

### ISSUE THREAD

**Issue by selajuf** [mishalhossin/Discord-AI-Chatbot#163]
I apologize for any inconvenience caused. It seems that there was an error preventing the delivery of my message.
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/88133431/7f7a083c-3d9d-4786-aa98-4eac89137eb2)
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/88133431/df54ab58-de5a-4937-8ac9-029c69d081f4)
how fix it?

**Comment by mishalhossin** [comment]
probly a problem with api  idk

**Comment by mishalhossin** [comment]
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/91066601/eea76b9b-5d1a-4e6c-870d-5ef0821cbee9)
Works tho

**Comment by selajuf** [comment]
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/88133431/79f2f93a-a410-4f08-9c2a-f0580b04739b)

**Comment by lu5her-s** [comment]
How to fix it
