### ISSUE TITLE
Error during image generation 

### ISSUE THREAD

**Issue by quantumwolf-git** [mishalhossin/Discord-AI-Chatbot#165]
The error was specific to only Imagine v4 Creative at first, but now it's there for all image generation modules.

```An error occurred while making the request: 400, message='Bad Request', url=URL('https://inferenceengine.vyro.ai/sdprem')
Traceback (most recent call last):
  File "/home/runner/JustChat/imaginepy/async_imagine.py", line 79, in sdprem
    async with self.session.post(
  File "/home/runner/JustChat/venv/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/runner/JustChat/venv/lib/python3.10/site-packages/aiohttp/client.py", line 643, in _request
    resp.raise_for_status()
  File "/home/runner/JustChat/venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://inferenceengine.vyro.ai/sdprem')```

**Comment by mishalhossin** [comment]
The api is down

**Comment by elricsilverhandx** [comment]
> The api is down

https://github.com/skzhengkai/vyro.ai-imagine

**Comment by elricsilverhandx** [comment]
https://api.vyro.ai/v1/imagine/web/generations

bearer : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMDVlNmJiNy0yYzc2LTRjZTMtOTA5NS1iZWFkYzhhZDYwZTEiLCJpYXQiOjE2ODc0MjAyOTAsImV4cCI6MTY4NzUwNjY5MH0.FH9Js_B31ZjHlhUToD53mNZROXQCbi0hV42pvzIfrfU

**Comment by elricsilverhandx** [comment]
yep api change and now fix

https://cdn.discordapp.com/attachments/1070678569887469691/1121383152317898782/image.png

**Comment by quantumwolf-git** [comment]
where to make the change, it still doesn't work for me?

**Comment by quantumwolf-git** [comment]
It still errors out the same way. Am I missing something?

**Comment by mishalhossin** [comment]
> It still errors out the same way. Am I missing something?

it should be fixed idk

**Comment by steph4041** [comment]
broke again 💀

**Comment by mishalhossin** [comment]
fixed
