### ISSUE TITLE
Bot used to work, started giving errors when spoken to it just today.

### ISSUE THREAD

**Issue by TwangyMoney** [mishalhossin/Discord-AI-Chatbot#175]
He seems to also spam this: 
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/87775970/19a9cd25-3549-4546-9e88-ca876aa36f43)
What happened?

2023-06-28 07:19:54 ERROR    discord.client Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/runner/Vega-on-Discord/venv/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 168, in on_message
    search_results = await search(message.content)
  File "/home/runner/Vega-on-Discord/utilities/ai_utils.py", line 26, in search
    search_query = await get_query(prompt)
  File "/home/runner/Vega-on-Discord/utilities/ai_utils.py", line 181, in get_query
    response = await generate_chat_completion(messages)
  File "/home/runner/Vega-on-Discord/utilities/ai_utils.py", line 109, in generate_chat_completion
    response_data = await response.json()
  File "/home/runner/Vega-on-Discord/venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://mishalsgpt.vercel.app/api/openai/v1/chat/completions')

**Comment by TwangyMoney** [comment]
ah, was expecting that. Is there a way to change the link to the one najmul's selfbot uses also i have him added on discord if we could discuss a solution to this you can add me @twangymoney on discord

**Comment by mishalhossin** [comment]
fixed

**Comment by TwangyMoney** [comment]
oh wa-wat wait but the- ah nvm almost had you damit

**Comment by mishalhossin** [comment]
> oh wa-wat wait but the- ah nvm almost had you damit

lol wdym

**Comment by mishalhossin** [comment]
> ah, was expecting that. Is there a way to change the link to the one najmul's selfbot uses also i have him added on discord if we could discuss a solution to this you can add me twangymoney on discord

join discord

**Comment by TwangyMoney** [comment]
nothing, I just really wanted to work with you and najmul in discord. and i did join discord. the bot is still not working

**Comment by mishalhossin** [comment]
> nothing, I just really wanted to work with you and najmul in discord. and i did join the discord. the bot is still not working

i think najmul is dead

**Comment by TwangyMoney** [comment]
He is definately not he only 5 mins ago gave me the invite link to your discord
