### ISSUE TITLE
nsfw note

### ISSUE THREAD

**Issue by nassro199** [mishalhossin/Discord-AI-Chatbot#176]
**you forget to add nsfw filter to the pollinations.ai command btw :)**

**Comment by mishalhossin** [comment]
> **you forget to add nsfw filter to the pollinations.ai command btw :)**

i like nsfw :)

**Comment by quantumwolf-git** [comment]
Bruh it's legit generating cporn with fetishes.

**Comment by Razex-SO** [comment]
update the github brother :'(

**Comment by mishalhossin** [comment]
Fixed

**Comment by quantumwolf-git** [comment]
pollination's output is sent as a private message, only visible to us. Is that intended?

**Comment by mishalhossin** [comment]
> pollination's output is sent as a private message, only visible to us. Is that intended?

yes
