### ISSUE TITLE
Image recognition no work

### ISSUE THREAD

**Issue by TwangyMoney** [mishalhossin/Discord-AI-Chatbot#180]
fix image recognition plsplsplsplspslpls1!!!!1!

I created an issue, now you have no choice but to fix it :3

**Comment by mishalhossin** [comment]
No

**Comment by TwangyMoney** [comment]
how dare you close this issue it's not resolved

**Comment by mishalhossin** [comment]
> 

closed as not planed

**Comment by TwangyMoney** [comment]
:(
