### ISSUE TITLE
Your Website is down

### ISSUE THREAD

**Issue by DaniEnsi** [mishalhossin/Discord-AI-Chatbot#188]
All chat completion is broken due to your website being down... Thanks for doing all this tough 💯

**Comment by mach7** [comment]
Wondering why things have to route through the https://mishalsgpt.vercel.app site.... What ever is there, can we also get a repo of it to self-host that ourselves? Or eliminate the need for that all together and put that source into this too?

**Comment by IntrovertedFL** [comment]
If you don't like how he does things then install oogabooga and use the api to make your own bot? Not many other options lol

**Comment by mach7** [comment]
What's the purpose of running it through vercel.app anyway, is it suppose to be a GPT4 proxy? 

I'd gladly install what ever the missing piece of the puzzle is if I can find it.

**Comment by mishalhossin** [comment]
> What's the purpose of running it through vercel.app anyway

vercel has edge servers so its fast i guess

**Comment by DaniEnsi** [comment]
> > Wondering why things have to route through the https://mishalsgpt.vercel.app site.... What ever is there, can we also get a repo of it to self-host that ourselves? Or eliminate the need for that all together and put that source into this too?
> 
> https://github.com/Yidadaa/ChatGPT-Next-Web

Figured this one already, but what are you using as your backend, like whats running under /openai/api/v1/completions. Reverse proxy I am guessing?! That would be great If you could share whats running there...
