### ISSUE TITLE
Unauthorised to deepai

### ISSUE THREAD

**Issue by Aryan2-1** [mishalhossin/Discord-AI-Chatbot#189]
I'm getting 401 status code while using deepai it's asking for apikey

**Comment by mishalhossin** [comment]
okay

**Comment by Aryan2-1** [comment]
Why did you close it tell me solution

**Comment by mishalhossin** [comment]
> Why did you close it tell me solution

i fixed it in latest commit

**Comment by Aryan2-1** [comment]
Now it's sending blank messages

**Comment by Aryan2-1** [comment]
It's returning empty messages

**Comment by Aryan2-1** [comment]
Response is empty

**Comment by mishalhossin** [comment]
ah shit here we go again

**Comment by Aryan2-1** [comment]
That's because I'm still getting unauthorised I checked it after removing try except
