### ISSUE TITLE
Instructions not working

### ISSUE THREAD

**Issue by CrystalVortex** [mishalhossin/Discord-AI-Chatbot#198]
The instructions do not work in the latest version.

**Comment by elricsilverhandx** [comment]
Openai changed and sexual or jailbreaked all instructions blocked.

**Comment by mishalhossin** [comment]
> Openai changed and sexual or jailbreaked all instructions blocked.

True
```py
https://platform.openai.com/docs/guides/moderation/overview?lang=python
```
