### ISSUE TITLE
APIError : "Bad context detected!"

### ISSUE THREAD

**Issue by itz-ankit** [mishalhossin/Discord-AI-Chatbot#202]
File "/home/runner/Discord-AI-Chatbot-mod/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 405, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: '{"detail":"Bad context detected!"}' (HTTP response code was 422)

any idea how to disable this "Bad Context detected!" ? :') cuz most of the times its not responding to the chats because of this.

**Comment by mishalhossin** [comment]
Yea api error
