### ISSUE TITLE
Instructions Wiki / Discussion

### ISSUE THREAD

**Issue by AbandonedCart** [mishalhossin/Discord-AI-Chatbot#208]
As is, the instructions do not really indicate the result. You have to read through them. You also have to customize some.

If you can only use one, does having multiple templates really make sense? Why not leave one, then use a wiki or discussion topic that tells how to make instructions to post more examples? 

If nothing else, it will cut down on a lot of work trying to review and merge every time an optional text file gets edited.

**Comment by mishalhossin** [comment]
i hate when i get email from github so i added it
