### ISSUE TITLE
Bot broke because of... ChatGPT_API?

### ISSUE THREAD

**Issue by saaandrew** [mishalhossin/Discord-AI-Chatbot#213]
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/86618490/1283fa58-8981-41a6-beb7-a75afb24866f)
yo @mishalhossin we got some API bug here

**Comment by saaandrew** [comment]
yes i do
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/86618490/6b197ca2-d779-4549-bfeb-d48599e3ce85)

**Comment by simonenkoilya** [comment]
Same problem.

**Comment by simonenkoilya** [comment]
This happens in 80% of cases, if you ask something from the bot.

**Comment by IntrovertedFL** [comment]
Happening for me as well, same error message around 80% of the time.

**Comment by mishalhossin** [comment]
```
DISCORD_TOKEN=MTEwNjQ2Mjc1OTA1NDYxOA.G433qg.o2YbC5KD6HNZ61n277bdx4IssByf7cNw
CHIMERA_GPT_KEY=F5vgxMDoRHqT_AG7d99esEbZG5JKXtWkpUtpfI
```
(Credential are invalidated)


Working for me tho

**Comment by mishalhossin** [comment]
> ![image](https://user-images.githubusercontent.com/86618490/256556203-1283fa58-8981-41a6-beb7-a75afb24866f.png) yo @mishalhossin we got some API bug here

It could be cause of your replit RAM being overloaded

**Comment by saaandrew** [comment]
nah man i pay them $20/mo to get a 4GB RAM per repl

**Comment by lu5her-s** [comment]
@saaandrew you add name of chimera invalid
you = CHIMERA_API_KEY
change to = CHIMERA_GPT_KEY

**Comment by saaandrew** [comment]
Oh f ok thanks
