### ISSUE TITLE
Switch to an alternative API

### ISSUE THREAD

**Issue by Eevee-Gaming** [mishalhossin/Discord-AI-Chatbot#218]
Hi, would like to ask if we can change API.
There is a LOT of chinese random people which are abusing the free API, and now there is a paywall of 10$ for a better API. Plus the ChimeraGPT community is weird and unhelpful at all. I keep getting 5 errors every minute, the free API is awfully unstable... So i would like to ask if there is some alternative way for fixing that, or an available API which isn't abused or paywalled.

Thank you in advance.

**Comment by Tassu2018** [comment]
Also, they kicked me out for like no reason, and now the invite link is now invalid so I can't even use their API anymore.

**Comment by ImShEthan** [comment]
Chimera is dead I think, no more discord & api

**Comment by mishalhossin** [comment]
> Same thing happened to me, they ended up kicking legitimate user instead of people who's abusing it, goddamn.

Th server got deleted

**Comment by Jim-m-y** [comment]
It would be great if you could make it work with the OpenAI api, the paid one, chimeragpt is down

**Comment by Jim-m-y** [comment]
> > Same thing happened to me, they ended up kicking legitimate user instead of people who's abusing it, goddamn.
> 
> Th server got deleted

It would be great if you could make it work with the OpenAI api, the paid one, chimeragpt is down

**Comment by mrcat-the-original** [comment]
> > Same thing happened to me, they ended up kicking legitimate user instead of people who's abusing it, goddamn.
> 
> Th server got deleted

I believe that's a fourth reason to consider switching to a different API.

**Comment by Eevee-Gaming** [comment]
> It would be great if you could make it work with the OpenAI api, the paid one, chimeragpt is down

It's too much, 20$ per month, jesus.

**Comment by Eevee-Gaming** [comment]
> Th server got deleted

They got banned from Discord, they did a backup tho, i'm in, however, the API is still extremely abused.

**Comment by elricsilverhandx** [comment]
https://discord.gg/2DmMUVSvSh

new chimeragpt v2 discord channel

**Comment by mrcat-the-original** [comment]
"**It appears that either they have faced another instance of suspension, or I myself have encountered a prohibition, as the server link has regrettably become invalid.**"

**Comment by Yarpopcat08** [comment]
> "**It appears that either they have faced another instance of suspension, or I myself have encountered a prohibition, as the server link has regrettably become invalid.**"

Same...

**Comment by mishalhossin** [comment]
true

**Comment by Eevee-Gaming** [comment]
This is unrelated but someone do have a free SDXL 1.0 API (or simply website) ? (No watermarks, no long waiting queue, working at least...)

Once i saw a playground full of painting AI that was open-source, however i don't remember the name. :/

**Comment by mishalhossin** [comment]
> This is unrelated but someone do have a free SDXL 1.0 API (or simply website) ? (No watermarks, no long waiting queue, working at least...)
> 
> Once i saw a playground full of painting AI that was open-source, however i don't remember the name. :/

https://zoo.replicate.dev/
