### ISSUE TITLE
Internet Search

### ISSUE THREAD

**Issue by HyperDeathh** [mishalhossin/Discord-AI-Chatbot#223]
![D72A22E4-FFAE-4F46-BE2D-37C7BBCE9708](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/62476124/a6c76acd-7c1a-4bd3-a7ee-d3163813b4a2)

internet not working after last update

**Comment by luciimon** [comment]
again.
An error occurred during the search request: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://ddg-api.herokuapp.com/search?query=
