### ISSUE TITLE
The bot fails to finish what it was saying because it got censored

### ISSUE THREAD

**Issue by H0wd3n** [mishalhossin/Discord-AI-Chatbot#224]
Sometimes when I ask the bot to say something or use the suzume instructions it errors out and doesn't respond because it tried to say something sexual or harassment etc. is there a way to bypass that?

**Comment by elricsilverhandx** [comment]
use llama-2-70b-chat all openai model blocked

**Comment by H0wd3n** [comment]
the only model that seems to work correctly is gpt-4 and it censors most of what the bot wants to say
