### ISSUE TITLE
chimera gpt discord link is broken

### ISSUE THREAD

**Issue by sn00wzz** [mishalhossin/Discord-AI-Chatbot#226]
the link is invalid

**Comment by mrcat-the-original** [comment]
> the link is invalid

They probably got banned again.

**Comment by BrandonBeast999** [comment]
> > the link is invalid
> 
> They probably got banned again.

so is the bot unfunctional until the discord link is back up? i have done everything else right I just need the openai chimera.

**Comment by mrcat-the-original** [comment]
> > > the link is invalid
> > 
> > 
> > They probably got banned again.
> 
> so is the bot unfunctional until the discord link is back up? i have done everything else right I just need the openai chimera.

The issue lies in the fact that Discord not only banned the **server** but also its **owner**. Therefore, it is highly unlikely that the API will be reinstated. I did hear about a Telegram group, though, but I'm not sure about it. ¯\_(ツ)_/¯
