### ISSUE TITLE
Disable chimera gpt

### ISSUE THREAD

**Issue by Fede14it** [mishalhossin/Discord-AI-Chatbot#227]
Is possible to disable chimeragpt because their discord has been cancelled?

**Comment by selajuf** [comment]
+. disable chimera please

**Comment by saaandrew** [comment]
Chimera is replaced by Naga.
Problem solved.

**Comment by Dron007** [comment]
Invites to Naga AI are rejected.

**Comment by RoboResponse** [comment]
[best Chatbots for live support](https://roboresponse.ai/blog/Six-best-OpenAI-chatbot-platforms.html) are a game-changer! They allow businesses to truly personalize user interactions, creating a unique and engaging experience [chatbots for e-commerce sales](https://roboresponse.ai/blog/Six-best-OpenAI-chatbot-platforms.html).

**Comment by mishalhossin** [comment]
Ok
