### ISSUE TITLE
self bot

### ISSUE THREAD

**Issue by quentingosset** [mishalhossin/Discord-AI-Chatbot#236]
Hey, i see your bot is working like a bot but is it possible to use it like a normal people on a norrmal Discord Account ?

**Comment by skzhengkai** [comment]
Here you go: https://github.com/mishalhossin/Discord-AI-Selfbot

Please note that this operation is extremely risky and can get your account terminated from Discord. I do not condone, support, or suggest using selfbots on Discord.
