### ISSUE TITLE
Issue with the translation system? "Something went wrong"

### ISSUE THREAD

**Issue by Chevels** [mishalhossin/Discord-AI-Chatbot#238]
Hello,
Since this weekend, Prism only responds in English even if you speak to it in another language (French for example).
If we insist that he respond in French, his responses all end with "`Something went wrong`", except for very rare exceptions.

I'll let you know the problem in case it helps.

Thank you for your work on the bot and good luck with the development!

![Capture d’écran 2023-10-31 131701](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/8831222/1efad1aa-3617-43d3-ae89-b0b64f70e489)
![Capture d’écran 2023-10-31 131735](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/8831222/1a62c9b7-420f-40e3-a01e-010c402555d8)

**Comment by mishalhossin** [comment]
Dosnt like speaking in forigen language also this isnt the repo for it

**Comment by Chevels** [comment]
Oh so I'm sorry to bother you, I thought it would be helpful for you if I created a way out. As the bot was working very well before this weekend, it responded perfectly well in French so I thought there was a problem.
So this means that the bot will never speak French again? (To know if you have to find another one).
