### ISSUE TITLE
internet search not working 

### ISSUE THREAD

**Issue by luciimon** [mishalhossin/Discord-AI-Chatbot#241]
An error occurred during the search request: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://ddg-api.herokuapp.com/search?query=...?&limit=0')

**Comment by elricsilverhandx** [comment]
When you make a call it will give an error. If you write this error, we will write you the solution.

**Comment by luciimon** [comment]
{'message': 'Repl not found. If you believe this is a mistake, try logging in to Replit first.', 'name': 'NotFoundError', 'status': 404}

URL : https://ddg-api.awam.repl.co/api/search

ai_utils.py

if search_query is not None:
           try:
            async with aiohttp.ClientSession() as session:
                async with session.get('https://ddg-api.awam.repl.co/api/search',
                                       params={'query': search_query, 'maxNumResults': search_results_limit}) as response:
                    search = await response.json()

**Comment by elricsilverhandx** [comment]
> {'message': 'Repl not found. If you believe this is a mistake, try logging in to Replit first.', 'name': 'NotFoundError', 'status': 404}
> 
> URL : https://ddg-api.awam.repl.co/api/search
> 
> ai_utils.py
> 
> if search_query is not None: try: async with aiohttp.ClientSession() as session: async with session.get('https://ddg-api.awam.repl.co/api/search', params={'query': search_query, 'maxNumResults': search_results_limit}) as response: search = await response.json()

API is down, we will create a new API connection in the next update.
