### ISSUE TITLE
How do I change the named on the models

### ISSUE THREAD

**Issue by JakeyCmh** [mishalhossin/Discord-AI-Chatbot#248]
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/110308558/9f445a6c-fb7e-4a7b-bba2-119fe1c989a5)

like the (HOLYSHIT THIS IS GOOD) part, I want to change that

**Comment by JakeyCmh** [comment]
another thing is, Some of the models dont even work like SDXL doesn't function, it just stays stuck on "thinking"

**Comment by Diboxa** [comment]
which models then work?

**Comment by mak448a** [comment]
> ![image](https://private-user-images.githubusercontent.com/110308558/297454937-9f445a6c-fb7e-4a7b-bba2-119fe1c989a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NDY3OTgsIm5iZiI6MTcwNjg0NjQ5OCwicGF0aCI6Ii8xMTAzMDg1NTgvMjk3NDU0OTM3LTlmNDQ1YTZjLWZiN2UtNGE3Yi1iYmEyLTExOWZlMWM5ODlhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwNDAxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2Y1ZTI3MTExYTgzNDI3ZGQ2MzBmZWVhOWFiZWY1OTI0MzQzZTE4NWRiMzBmYjk5MGM5YzI1NWUyOGNkMWIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZlPz_4KckNdyy7scyQEZL8hD_yMfWMbGmHytncHQ6xI)
> 
> like the (HOLYSHIT THIS IS GOOD) part, I want to change that

Go to this python file in your local copy and edit it:
https://github.com/mishalhossin/Discord-AI-Chatbot/blob/96e9befc014317b86b557b30db9c4f35f2fe5f0d/main.py#L288
