### ISSUE TITLE
(API Chnage) Use My custom LM Studio Public API, Its totally FREE forever

### ISSUE THREAD

**Issue by windows11-on-web** [mishalhossin/Discord-AI-Chatbot#249]
As of right now, the endpoint right now sucks. If you want a better free stable api. Look into PortKVM Project and see that Public sweet endpoint, 

Props you need:
- config yaml ai model must be set to "local-model"
- go to your bot utills and edit ai_utils.py and edit the line with `base_url = 'garbage api'` , with my api, Use this `public-lmstudio.server.shreesmart.buzz`., Done
```
openai_client = AsyncOpenAI(
    api_key = os.getenv('CHIMERA_GPT_KEY'),
    base_url = "https://api.naga.ac/v1"
)
```

And let me tell you, Its an UNCENSORED model, Yes you heard that right, UNCENSORED. But i need to tell you a few fallbacks
- no imagine (Yes, no imagine, uwu)
- no other models than dolphin 2.5 1.1B Q8.0 guff
- Slow, We are gonna upgrade hardware soon to 64GB+ RAM, Sorry!

**Comment by windows11-on-web** [comment]
Also you dont need API Key or sign up

**Comment by mishalhossin** [comment]
its offline tho
