### ISSUE TITLE
bot keeps going offline

### ISSUE THREAD

**Issue by lumiboi** [mishalhossin/Discord-AI-Chatbot#252]
What should I do to make the bot always online? should I run it manually all the time?

**Comment by elricsilverhandx** [comment]
If you write the error before it closes, we will write you the solution.

**Comment by lumiboi** [comment]
> If you write the error before it closes, we will write you the solution.

I don't get any errors. as soon as I close poweshell the bot goes offline. do I have to run it manually all the time?

**Comment by elricsilverhandx** [comment]
Try cmd

**Comment by mishalhossin** [comment]
dumb dumb

**Comment by lumiboi** [comment]
> Refere

u're a little tense, i think.

**Comment by itsidleboy** [comment]
bro just keep the power shell open in background.
