### ISSUE TITLE
Responses getting cut off and bot only replying to older messages when using custom instruction file on Claude API

### ISSUE THREAD

**Issue by joep1000** [mishalhossin/Discord-AI-Chatbot#255]
Hi! I have been happily using your Discord bot and have noticed an issue with the bot's responses. The problem occurs when I ask the bot a question with the Claude API (claude-3-opus-20240229, but it happens with every variant of the claude models i've tried) and a custom instruction file. First, it provides a good response. However, when I ask a follow-up question, the bot's response gets cut off, and it seems to reply only to older messages instead of the most recent one and ignores your new request entirely. This does not occur when I use another API like gpt-4-turbo.

An example:
I ask the bot: "Is the ACER Nitro N50-650 Gaming PC - Intel® Core™ i5, RTX 4060, 1 TB SSD good for gaming and game development?"
Claude provides a good answer to this question.
I then ask a different question, but the bot's response is cut off, and it only replies to the older message about the gaming PC, even though the new question was sent successfully.
I think it's an issue with how the bot handles the conversation history or processes subsequent questions. The responses are getting truncated, and the bot is getting confused, replying to older messages instead of the most recent one. Might be related to the on_message event in the main.py file, specifically in how the responses are generated and sent back. 

I have included some screenshots of what I mean.
First screenshot: good reply
<img width="842" alt="Screenshot 2024-03-25 at 21 57 48" src="https://github.com/mishalhossin/Discord-AI-Chatbot/assets/131517053/ef7a32f8-174e-4215-bff2-7c77b29f22ba">

Second screenshot: old/bad reply to a different question that is related to the custom instructions file.

<img width="842" alt="Screenshot 2024-03-25 at 21 57 56" src="https://github.com/mishalhossin/Discord-AI-Chatbot/assets/131517053/df184b7a-8640-4617-a5fa-ea246e455c7c">

Third screenshot: the correct reply that I specified in the custom instruction file after I asked the bot the same question a second time via claude.

<img width="711" alt="Screenshot 2024-03-25 at 21 58 03" src="https://github.com/mishalhossin/Discord-AI-Chatbot/assets/131517053/3ecad607-9263-4fc7-bd24-c1a6aa854f4b">

**Comment by joep1000** [comment]
<img width="731" alt="Screenshot 2024-03-25 at 22 03 09" src="https://github.com/mishalhossin/Discord-AI-Chatbot/assets/131517053/796ec7ef-bb0e-4f41-a8eb-8af7d0c44c15">

The reply from Claude is also cut off at the end sometimes, as you can see here the discord emote specified in the custom instructions file is not completed by Claude

**Comment by mishalhossin** [comment]
discord message character limit i will try make it split the message and not cut of characters

**Comment by joep1000** [comment]
> discord message character limit i will try make it split the message and not cut of characters

Thanks for your work! Sorry to keep bothering you, but I updated it with your new code and now I'm getting hit by a random rate limit even though the old code seems to think the rate limit is still fine and works properly (besides the messages getting cut off of course):

new code:
<img width="573" alt="Screenshot 2024-04-03 at 18 27 58" src="https://github.com/mishalhossin/Discord-AI-Chatbot/assets/131517053/9a255682-17a8-40be-af0e-14461223a2c5">

same message sent with old code and same AI set in config.yml (claude-3-opus-20240229):
<img width="701" alt="Screenshot 2024-04-03 at 18 28 42" src="https://github.com/mishalhossin/Discord-AI-Chatbot/assets/131517053/39cb309d-d146-45f4-b9b0-b79ab968958e">
