### ISSUE TITLE
Including unnecessary closing tags in the reponse

### ISSUE THREAD

**Issue by AmbroseSilverWolfe** [mishalhossin/Discord-AI-Chatbot#264]
![Screenshot_2024-04-24-04-46-08-48_572064f74bd5f9fa804b05334aa4f912](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/47878316/a13ce4ea-3e9a-42e3-8209-f8ae1e5d7add)
The AI seems to be including these tags in the response. Sometimes multiple (as seen here) sometimes just one. And sometimes none at all

**Comment by mishalhossin** [comment]
The is because of the prompt template the groq uses

**Comment by mishalhossin** [comment]
Try switching models
