### ISSUE TITLE
[Possible Enhancement] Add internet access

### ISSUE THREAD

**Issue by Zalatis** [mishalhossin/Discord-AI-Chatbot#46]
As the title says, would be nice if possible to add internet access to the bot
Maybe using a webcrawler and give the page content to the bot idk

**Comment by mishalhossin** [comment]
> As the title says, would be nice if possible to add internet access to the bot Maybe using a webcrawler and give the page content to the bot idk

Webcrawler huh ? which one?

**Comment by Zalatis** [comment]
I was thinking of maybe using like selenium, puppeteer or something like this
In this way the bot would be able to summarize the user's request if it exceeds 2021 and thus obtain the answer from the internet directly

Maybe it's not the best approach of how to do this but at the moment I only have this idea
