### ISSUE TITLE
What am i supossed to rename example.env to?

### ISSUE THREAD

**Issue by cqyber** [mishalhossin/Discord-AI-Chatbot#72]
U Cannot just rename it to .env, and without it i get a incorrect token passed error.

**Comment by mishalhossin** [comment]
if you cant rename then create a new file named .env


and if you are using replit check the secrets tab and add it
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/91066601/b1ec280c-79f6-4883-9ca6-b195086c0d69)

**Comment by ImN3k0** [comment]
check that file extensions are viewable before attempting to rename the file.
or as mishalhossin said, use replit.
if new to replit or tokens.
click secrets tab in tools section in the picture.
new secret = "HUGGING_FACE_API"/"DISCORD_TOKEN" without quotes. 
value = Your appropriate key.
you can find and get the tokens by following the instructions in the description of the "<>code" page

hope this helps.
