### ISSUE TITLE
Bot isn't responding 

### ISSUE THREAD

**Issue by Gobin20** [mishalhossin/Discord-AI-Chatbot#75]
As the title says

I see that the bot is typing, however I never get a response. I tried to restart the service, however no luck. Should I re-download the repository?

**Comment by Gobin20** [comment]
It does response to /bonk and /ping yet no response

**Comment by techett** [comment]
Experiencing similar behavior. When put under multiple requests at once the bot will start sending error messages
<img width="716" alt="Screenshot 2023-05-17 at 4 01 10 PM" src="https://github.com/mishalhossin/Discord-AI-Chatbot/assets/30886852/60a03dd2-b96c-4002-8b3d-7846b95fceb1">

Will report back later.

**Comment by mishalhossin** [comment]
Ima just use chatbase then
