### ISSUE TITLE
Spacing issue

### ISSUE THREAD

**Issue by enemyalert** [mishalhossin/Discord-AI-Chatbot#85]
is there any way to make this text look more neat and organized? bulleting/numbering should have spacing.

**Comment by enemyalert** [comment]
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/74367697/91134704-6ea2-47cd-99f9-6c67092eb54b)

**Comment by mishalhossin** [comment]
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/91066601/9f49b228-02ed-412c-80ef-b5178da9cdb7)
