### ISSUE TITLE
Hugging Face Key Error

### ISSUE THREAD

**Issue by Needthisplz** [mishalhossin/Discord-AI-Chatbot#86]
when I try to run the main.py this is the error I get:

Traceback (most recent call last):
  File "/home/michael/Discord-AI-Chatbot/main.py", line 126, in <module>
    api_key = os.environ['HUGGING_FACE_API']
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'HUGGING_FACE_API'

**Comment by mishalhossin** [comment]
you didnt add HUGGING_FACE_API to .env file

you can get it here https://huggingface.co/settings/tokens

**Comment by mishalhossin** [comment]
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/91066601/61adbc69-aff5-4ce7-a1ef-ff579212082e)

**Comment by Needthisplz** [comment]
I put it in there, it didn't work.

**Comment by mishalhossin** [comment]
> I put it in there, it didn't work. i appreciate your answering though.

are you putting in `.env` or `example.env` ?

**Comment by Needthisplz** [comment]
> > I put it in there, it didn't work. i appreciate your answering though.
> 
> 
> 
> are you putting in `.env` or `example.env` ?

I changed it to .env like you said.

**Comment by Needthisplz** [comment]
> > I put it in there, it didn't work. i appreciate your answering though.
> 
> 
> 
> are you putting in `.env` or `example.env` ?

It's working now! Thank you!

**Comment by mishalhossin** [comment]
hugging face key is no longer needed or used
