### ISSUE TITLE
Wrong informations and generated code not properly sent using markdown

### ISSUE THREAD

**Issue by Zalatis** [mishalhossin/Discord-AI-Chatbot#87]
It looks like when you ask for generating code it doesn't properly be send to discord, example : 

![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/16846453/e82ec252-6397-4210-b7eb-60dc86962069)

1 day late
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/16846453/503568d8-d109-4e8e-8ab2-275bb4cf29e0)

**Comment by mishalhossin** [comment]
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/91066601/264125a4-2fd0-4aaa-b132-db2bed1bc6bb)
