### ISSUE TITLE
OCR for images

### ISSUE THREAD

**Issue by Scopinou** [mishalhossin/Discord-AI-Chatbot#90]
Hello,

When I ask the bot to solve a OCR for images, I got that answer :
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/91017052/61604284-af86-4f33-a041-3b5f53e0981e)

Here is the error on the console :
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/91017052/1a5d565d-e5c4-4576-8b64-7b721639a71c)

I have already set hugging face api key.

**Comment by mishalhossin** [comment]
> Hello,
> 
> When I ask the bot to solve a OCR for images, I got that answer : ![image](https://user-images.githubusercontent.com/91017052/239732708-61604284-af86-4f33-a041-3b5f53e0981e.png)
> 
> Here is the error on the console : ![image](https://user-images.githubusercontent.com/91017052/239732752-1a5d565d-e5c4-4576-8b64-7b721639a71c.png)
> 
> I have already set hugging face api key.

try again in like 5 seconds

**Comment by Scopinou** [comment]
Sometimes, it seems to work, sometimes not.
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/91017052/ff3581fe-a32f-4789-a550-882e475b6035)

`[Exception('API request failed with status code 503: {"error":"Model microsoft/trocr-base-printed is currently loading","estimated_time":20.0}'), [{'generated_text': 'a sign that says "don\'t miss the holidays" '}]]`

**Comment by mishalhossin** [comment]
> Sometimes, it seems to work, sometimes not. ![image](https://user-images.githubusercontent.com/91017052/239756195-ff3581fe-a32f-4789-a550-882e475b6035.png)
> 
> `[Exception('API request failed with status code 503: {"error":"Model microsoft/trocr-base-printed is currently loading","estimated_time":20.0}'), [{'generated_text': 'a sign that says "don\'t miss the holidays" '}]]`

Hmm i should try to make the model stay awake by sending GET request every 1 minutes with timeout of 30
