### ISSUE TITLE
hey you forgot a module

### ISSUE THREAD

**Issue by saaandrew** [mishalhossin/Discord-AI-Chatbot#93]
Hey, I got in bit of trouble when trying to start up my bot when i realized there was a module that is missing in the "requirements.txt" named: "requests-toolbelt"
I pip installed the requests-toolbelt and everything is fine now
You should add the module above to the "requirements.txt" file because you're using it in the "/imaginepy/sync_imagine.py" file.
Peace!

![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/86618490/6e6e4e6d-c3ca-40a0-a2cc-d4a42a9ded69)

**Comment by Gobin20** [comment]
Ran into the same problem, however adding requests_toolbelt did solve this bug.

Add requests_toolbelt if you run into the same problem

**Comment by mishalhossin** [comment]
My bad bbg
