### ISSUE TITLE
/imagine 

### ISSUE THREAD

**Issue by Gobin20** [mishalhossin/Discord-AI-Chatbot#95]
I love the new imagine option, however its to anime style for me. How could we change that?

**Comment by mishalhossin** [comment]
> I love the new imagine option, however its to anime style for me. How could we change that?

There is a new pull request that dose that

I will marge it when i get home

**Comment by mishalhossin** [comment]
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/91066601/bfc0e605-fa3a-4a21-b742-8694c6162237)

**Comment by mishalhossin** [comment]
Added that in #94
