### ISSUE TITLE
Error while deployment 

### ISSUE THREAD

**Issue by Gobin20** [mishalhossin/Discord-AI-Chatbot#97]
File "/home/pi123/Discord-AI-Chatbot/main.py", line 342
    @app_commands.choices(style=[
                          ^
SyntaxError: expression cannot contain assignment, perhaps you meant "=="?

This piece of code is giving. However checking the code i see that there is a comma missing between comic book and Imagine v4 creative

**Comment by Gobin20** [comment]
Adding the comma's does fix it

**Comment by Gobin20** [comment]
Add comas in main.py from line 357 till 367. And 374

**Comment by mishalhossin** [comment]
fixed
